apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Authorization
  template:
    metadata:
      labels:
        app: Authorization
    spec:
      containers:
      - name: authorizationrepos
        image: policycr.azurecr.io/authorizationrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: authorization
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Authorization
